[khan_flatflat38]
title = "경향신문 ─ 플랫"
url = "http://www.khan.co.kr/reporter_article.html?id=584"
entrySelector = "ul.list_df li"
titleSelector = "strong.tit_thumb.line_clamp3"
linkSelector = "a.link_cont"
contentSelector = "span.lead"
dateSelector =  "span.info_area span.byline em.letter"
dateFormat = "yyyy. MM. dd hh:mm"
imageSelector = "img.thumb_g"
waitForSelector = "ul.list_df li"
onFail = "stale"

[khan_flatflat38_hot]
title = "경향신문 ─ 플랫"
url = "http://www.khan.co.kr/reporter_article.html?id=584"
entrySelector = "ul.issue_reco_list li"
titleSelector = "p.title"
linkSelector = "a.tgm_best_article"
contentSelector = "p.date"
dateSelector =  "p.date"
dateFormat = "yyyy. MM. dd"
imageSelector = "img.thumb"
waitForSelector = "ul.issue_reco_list li"
onFail = "stale"

[khan_series_as257]
title = "경향신문 ─ 연재 ─ 플랫"
url = "https://www.khan.co.kr/series/articles/as257"
entrySelector = "ul.df-list li"
titleSelector = "h2.tit a"
linkSelector = "h2.tit a"
contentSelector = "a.line_clamp2"
imageSelector = "a picture img"
waitForSelector = "ul.df-list li"
onFail = "stale"

[hankookilbo_herstory]
title = "한국일보 ─ 뉴스레터 ─ 허스토리"
url = "https://www.hankookilbo.com/NewsLetter/herstory"
entrySelector = "ol.newjam-list li.newjam-item"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "p.lead"
imageSelector = "div.thumb img"
waitForSelector = "li.newjam-item"
onFail = "stale"

[ildaro]
title = "일다 ─ 전체기사"
url = "https://ildaro.com/sub_view.html"
entrySelector = "div.masonry div.news_list.masonry-brick"
titleSelector = "dd.title"
linkSelector = "dt a.link"
contentSelector = "dd.body a.link"
dateSelector =  "span.wdate"
dateFormat = "yyyy.MM.dd hh:mm"
imageSelector = "img.p_w"
waitUntil = "networkidle"
onFail = "stale"